### ISSUE TITLE
BUG: algorithm implementation mask shape

### ISSUE THREAD

**Issue by suenalaba** [HiIAmTzeKean/Streamsight#96]
When we get_data, the data is of InteractionMatrix type. This can't be transmitted using HTTP. We need to first convert it to a dataframe and transmit it as a JSON.
```
from streamsight.matrix import InteractionMatrix

data = evaluator.get_data(external_model_id)

df = data.copy_df() #get df to transmit as json

training_im = InteractionMatrix(df, item_ix='iid', user_ix='uid', timestamp_ix='ts') # reparse as IM after transmitting through network
training_im.mask_shape() # if i dont mask the shape: AttributeError: InteractionMatrix has no shape attribute. Please call mask_shape() first.

external_model.fit(training_im)


unlabeled_data = evaluator.get_unlabeled_data(external_model_id)
unlabeled_df = unlabeled_data.copy_df() # get df to transmit unlabeled data as json

unlabeled_im = InteractionMatrix(unlabeled_df, item_ix='iid', user_ix='uid', timestamp_ix='ts') # transform df back to IM after transmitting through network
unlabeled_im.mask_shape() #AttributeError: InteractionMatrix has no shape attribute. Please call mask_shape() first. if mask_shape() isn't called
```

However, after calling mask_shape the following throws error:
```
prediction = external_model.predict(unlabeled_im)
```

Error:
```
ValueError: dimension mismatch
```

If mask_shape() is not called:
The following error is thrown:
```
AttributeError: InteractionMatrix has no shape attribute. Please call mask_shape() first.
```

**Comment by suenalaba** [comment]
Running pip freeze > requirements.txt:
```
streamsight==0.2.8a0
```

**Comment by HiIAmTzeKean** [comment]
the error that you get is cause you get the df then try to create another IM which doesnt have the shape attribute. The evaluator should handle the shape attribute as the shape is private and should be only known to the evaluator. refer to run [5] and [7] it should be a get data which will give you the IM, once you get the DF out, you will lose all the meta data


```
from streamsight.matrix import InteractionMatrix

data = evaluator.get_data(external_model_id)

df = data.copy_df()

training_im = InteractionMatrix(df, item_ix='iid', user_ix='uid', timestamp_ix='ts')
```

running the above will cause the meta data in IM to be lost. note that DF does not hold the meta data of released ID and unknown ID

instead you should be using the data obtained from `evaluator.get_data(external_model_id)`

**Comment by suenalaba** [comment]
Will transmit both shape and df to reconstruct the exact same IM
